### ISSUE TITLE
Pyhton error

### ISSUE THREAD

**Issue by gioman** [jorgealmerio/valuetool#18] opened 2021-07-19 10:08 UTC
```
ZeroDivisionError: float division by zero 
Traceback (most recent call last):
  File "/home/giovanni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/valuetool/valuewidget.py", line 432, in printValue
    rowCol = self.getRowCol(layer, pos)
  File "/home/giovanni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/valuetool/valuewidget.py", line 303, in getRowCol
    xres = extent.width() / layer.dataProvider().xSize()
ZeroDivisionError: float division by zero
```

This happens when in a project there is a layer loaded with the "QuickMapServices" plugin or any other XYZ tiles layer loaded directly with QGIS.

**Comment by jfbourdon** [comment] 2021-07-21 14:47
Strange... I can't reproduce on my side but I can't see why. You can test my [branch](https://github.com/jfbourdon/valuetool/tree/layer_validity_check) to check if the problem is still there.

**Comment by gioman** [comment] 2021-07-21 15:24
> Strange... I can't reproduce on my side but I can't see why. You can test my [branch](https://github.com/jfbourdon/valuetool/tree/layer_validity_check) to check if the problem is still there.

@jfbourdon no error with this branch.

**Comment by jorgealmerio** [comment] 2021-07-21 15:51
I can not reproduce too !
But I use windows 7 and Qgis 3.18. 
Anyway I merged the pull request and I hope it solves!
Please @gioman let me know!

**Closed as completed** 2021-09-09 12:13 UTC

**Comment by gioman** [comment] 2021-09-09 13:52
@jorgealmerio I confirm it fixed, thanks!

**Comment by jorgealmerio** [comment] 2021-09-09 14:50
Thank you!
